# Generated by Django 2.2.3 on 2019-07-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20190708_1336'),
        ('pdi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdicategory',
            options={'verbose_name': 'PDI Category', 'verbose_name_plural': 'PDI Categories'},
        ),
        migrations.AddField(
            model_name='snag',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Unit'),
            preserve_default=False,
        ),
    ]
