# Generated by Django 2.2.3 on 2019-07-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi', '0002_auto_20190709_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snag',
            name='snag_no',
        ),
        migrations.AddField(
            model_name='snag',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
