# Generated by Django 2.2.3 on 2019-07-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi', '0003_auto_20190721_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='snag',
            name='snag_no',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
