# Generated by Django 2.2.3 on 2019-07-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdi', '0004_snag_snag_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snag',
            old_name='visit_datetime',
            new_name='snag_datetime',
        ),
    ]
