# Generated by Django 2.2.3 on 2019-07-21 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdi', '0005_auto_20190721_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snag',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snags', to='projects.Unit'),
        ),
    ]
