# Generated by Django 2.2 on 2019-06-28 09:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190628_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='primary_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter valid phone number with country/area code', max_length=128, region=None, verbose_name='Primary Phone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='secondary_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter valid phone number with country/area code', max_length=128, null=True, region=None, verbose_name='Secondary Phone'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CUSTOMER'), (2, 'CRM'), (3, 'DESIGN'), (4, 'CONSTRUCTION'), (5, 'ADMIN')], default=1, primary_key=True, serialize=False),
        ),
    ]
