# Generated by Django 2.2.2 on 2019-06-29 08:41

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190628_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address1',
            field=models.CharField(default='address1', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='address2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(default='Bangalore', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=django_countries.fields.CountryField(default='India', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='zip_code',
            field=models.CharField(default=327801, max_length=12, verbose_name='ZIP/Postal Code'),
            preserve_default=False,
        ),
    ]
