# Generated by Django 2.2.2 on 2019-06-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_unit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='project',
        ),
    ]
