# Generated by Django 2.2.2 on 2019-06-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_unit_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='tower',
            new_name='project_tower',
        ),
    ]
