# Generated by Django 2.2.3 on 2019-07-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_unit_owners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='owners',
            new_name='owner',
        ),
    ]
