# Generated by Django 2.2.3 on 2019-07-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20190703_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
