# Generated by Django 2.2.3 on 2019-07-14 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20190708_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='owned_units', to=settings.AUTH_USER_MODEL),
        ),
    ]
