# Generated by Django 2.2.3 on 2019-07-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': 'Library', 'verbose_name_plural': 'Libraries'},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='documents',
        ),
    ]
