# Generated by Django 2.2.3 on 2019-07-15 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20190714_2254'),
        ('libraries', '0002_auto_20190709_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Unit'),
        ),
    ]
