# Generated by Django 2.2.3 on 2019-07-15 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0004_document_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='published',
            field=models.BooleanField(default=False, help_text='Once published, document is visible to customers.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='document',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='projects.Unit'),
        ),
    ]
