# Generated by Django 2.2.3 on 2019-07-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0005_auto_20190715_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='documents',
            new_name='file',
        ),
    ]
