# Generated by Django 2.2.3 on 2019-07-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Project Status',
                'verbose_name_plural': 'Project Status',
            },
        ),
        migrations.CreateModel(
            name='UnitStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Unit Status',
                'verbose_name_plural': 'Unit Status',
            },
        ),
    ]
