# Generated by Django 2.2.3 on 2019-07-08 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0014_auto_20190708_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(2, 'Closed'), (1, 'Open')], default=1, max_length=20)),
                ('description', models.CharField(max_length=2000)),
                ('demand_date', models.DateField(auto_now_add=True, verbose_name='Demand Date')),
                ('demand_letter', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Demand Letter')),
                ('receipt', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Unit')),
            ],
        ),
    ]
