# Generated by Django 2.2.3 on 2019-07-15 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0005_auto_20190708_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand', to='projects.Unit'),
        ),
    ]
